kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: us.gcr.io/cloudrun-284100/road-to-kubernetes
    registry: us.gcr.io 
    auto_tag: true
    username: _json_key
    password:
      from_secret: gcr_password
  when:
    branch:
    - main
