kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: us.gcr.io/cloudrun-284100/road-to-kubernetes
    registry: us.gcr.io 
    tag: ${DRONE_COMMIT_SHA}
    username: _json_key
    password:
      from_secret: gcr_password
  when:
    branch:
    - main
- name: terraform
  image: hashicorp/terraform
  commands:
  - echo "hello!"
