kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: us.gcr.io/cloudrun-284100/road-to-kubernetes
    registry: us.gcr.io 
    tag: ${DRONE_COMMIT_SHA}
    username: _json_key
    password:
      from_secret: gcr_password
  when:
    branch:
    - main
- name: terraform
  image: hashicorp/terraform
  environment:
    GOOGLE_KEY:
      from_secret: gcr_password
    GOOGLE_APPLICATION_CREDENTIALS: /key.json
    TF_VAR_image_tag: ${DRONE_COMMIT_SHA}
  commands:
  - printf "%s" "$${GOOGLE_KEY}" > /key.json
  - cd terraform
  - terraform init
  - terraform apply -auto-approve
