kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: nsmith5/road-to-kubernetes
    auto_tag: true
    username: nsmith5
    password:
      from_secret: docker_password
  when:
    branch:
    - main
