kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: nsmith5/road-to-kubernetes
    auto_tag: true
    username: nsmith5
    password:
      from_secret: docker_password
  when:
    branch:
    - main
- name: deploy
  image: fedora:32
  environment:
    SSH_KEY:
      from_secret: deploy_key
  commands:
  - dnf install openssh-clients -y
  - eval `ssh-agent`
  - ssh-add - <<< $$SSH_KEY
  - ssh o "StrictHostKeyChecking=no" root@road-to-kubernetes.nfsmith.ca "pushd /opt/road-to-kubernetes && git pull && docker-compose build && docker-compose restart web && popd"
  when:
    branch:
    - main
