version: "3.8"
services:
  web:
    build: .
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - BIND_ADDRESS=0.0.0.0
    - BIND_PORT=5000
    ports:
    - "5000:5000"
  redis:
    image: "redis:alpine"
