apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "us.gcr.io/cloudrun-284100/road-to-kubernetes:{{ .Values.image.tag }}"
          env:
          - name: BIND_ADDRESS
            value: "0.0.0.0"
          - name: BIND_PORT
            value: "5000"
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
